name: egypto_ai
description: "An Egyptian AI Assistant"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.3
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  flutter_svg: ^2.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  get_it: ^8.0.3
  awesome_dio_interceptor: ^1.3.0
  intl: ^0.20.2
  equatable: ^2.0.7
  gpt_markdown: ^1.0.19
  google_sign_in: ^6.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  build_runner: 2.4.15
  retrofit_generator: ^9.2.0
  flutter_localization: ^0.3.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_512.png" # Default icon for older Android versions
  adaptive_icon_foreground: "assets/images/logo_512.png" # Foreground layer for adaptive icon
  adaptive_icon_background: "#0D0D0D" # Background color (or use an image path)

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/logo_512.png
  ios: true
  android: true
  fullscreen: true


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # ...existing code...

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf

    - family: SomarSans
      fonts:
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Somar Sans/TTF/Standard/SomarSans-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


dependency_overrides:
  analyzer: ^6.2.0