// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-xVo1rg2uiEruqCUAtoaL7DC9vMFoah8',
    appId: '1:949169566044:web:62ef1129b2344da2199199',
    messagingSenderId: '949169566044',
    projectId: 'egypto-ai',
    authDomain: 'egypto-ai.firebaseapp.com',
    storageBucket: 'egypto-ai.firebasestorage.app',
    measurementId: 'G-ZCXHWWTX4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyv3EMPncotfFnbcftscUSZSerO8G558',
    appId: '1:949169566044:android:f0df61c93e0c5a40199199',
    messagingSenderId: '949169566044',
    projectId: 'egypto-ai',
    storageBucket: 'egypto-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OIaTjgHkaF7ZEzfqLwpnXpKa6jV85nU',
    appId: '1:949169566044:ios:e3f74c0a6296f137199199',
    messagingSenderId: '949169566044',
    projectId: 'egypto-ai',
    storageBucket: 'egypto-ai.firebasestorage.app',
    iosBundleId: 'com.anas.egyptoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OIaTjgHkaF7ZEzfqLwpnXpKa6jV85nU',
    appId: '1:949169566044:ios:e3f74c0a6296f137199199',
    messagingSenderId: '949169566044',
    projectId: 'egypto-ai',
    storageBucket: 'egypto-ai.firebasestorage.app',
    iosBundleId: 'com.anas.egyptoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-xVo1rg2uiEruqCUAtoaL7DC9vMFoah8',
    appId: '1:949169566044:web:20af2c17cb11fa7e199199',
    messagingSenderId: '949169566044',
    projectId: 'egypto-ai',
    authDomain: 'egypto-ai.firebaseapp.com',
    storageBucket: 'egypto-ai.firebasestorage.app',
    measurementId: 'G-4DSD78HPTJ',
  );
}
